version: '3.8'

services:
  postgres:
    extends:
      file: backend-services.yml
      service: postgres

  beer_buddy_api:
    # The root directory from which we're building.
    build:
      context: .
      dockerfile: ./beer-buddy-api/Dockerfile

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - ./beer-buddy-api:/app:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - 3000:3000

    # Specify that this container depends on the other
    # container which we've called "database".
    depends_on:
      - postgres

    # Specify the values of the environment variables
    # used in this container.
    env_file:
      - .env